application:
  name: demo

database:
  username: foo
  password: bar

publicHttpServer:
  port: 8080
  requestTimeout: 30
  readTimeout: 30
  writeTimeout: 30

privateHttpServer:
  port: 8081
  requestTimeout: 30
  readTimeout: 30
  writeTimeout: 30